# 1.3.1

In [20]:
import numpy as np

rows = 8
columns = 8

mat = np.zeros(rows*columns).reshape(rows, columns)

for n in range(rows):
    for m in range(n%2, columns, 2):
        mat[n, m] = 1
        
print(mat)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 1.3.2

In [21]:
import numpy as np

def divide5(n):
    return n%5

mat = divide5(np.arange(25).reshape(5, 5))

print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3

In [22]:
import numpy as np

mat = np.random.random((3,3,3))

print(mat)

[[[6.61077123e-01 2.17786661e-01 9.89944413e-01]
  [9.93693599e-01 1.81928471e-01 5.39003794e-01]
  [7.55140274e-01 7.16947423e-01 5.84287288e-01]]

 [[4.46157058e-01 6.91202807e-01 6.66514701e-01]
  [5.07173151e-01 4.22300374e-01 3.72783025e-01]
  [6.24614943e-01 6.79642832e-01 5.16213879e-02]]

 [[6.26974228e-01 6.36541215e-01 7.22066863e-01]
  [8.04314562e-01 2.12650719e-01 3.98971889e-04]
  [4.58831191e-01 2.33822514e-01 7.47130293e-01]]]


# 1.3.4

In [23]:
import numpy as np

rows = 8
columns = 8

mat = np.zeros(rows*columns).reshape(rows, columns)

for i in range(columns):
    mat[0, i] = 1
for i in range(columns):
    mat[rows-1, i] = 1
for i in range(rows):
    mat[i, 0] = 1
for i in range(rows):
    mat[i, columns-1] = 1
        
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# 1.3.5

In [24]:
import numpy as np

mat = np.random.random((10))
mat = np.sort(mat)[::-1]

print(mat)

[0.84046096 0.78532652 0.74696752 0.64050185 0.46456856 0.44291681
 0.41180127 0.21943759 0.15483886 0.06483211]


# 1.3.6

In [25]:
import numpy as np

mat = np.random.random((10, 9, 8))

print('shape = ', mat.shape)
print('dim = ', mat.ndim)

shape =  (10, 9, 8)
dim =  3


# 2.3.1

In [26]:
import pandas as pd
from math import sqrt

a = pd.Series({'x': 1, 'y': 1})
b = pd.Series({'x': 5, 'y': 4})

d = sqrt((b['x']-a['x'])**2+(b['y']-a['y'])**2)

print(d)

5.0


# 2.3.2

In [12]:
import pandas as pd

url = "https://github.com/akmand/datasets/raw/main/adult.csv"

file = pd.read_csv(url)

file

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec-managerial        Husband  White    Male              13   
2      Handlers-cleaners  Not-in-family  White    Male              40   
3      Handlers-cleaners        Husband  Other    Male              40   
4         Prof-specialty           Wife  Other  Female              40   
...                  ...            ...    ...     ...             ...   
45217     Prof-specialty      Own-child  White    Male              40   
45218     Prof-specialty  Not-in-family  White  Female              36   
45219     Prof-specialty        Husband  White    Male              50   
45220       Adm-clerical      Own-child  Other    Male              40   
45221    Exec-managerial        Husband  White    Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
4              Other        0         <=50K  
...              ...      ...           ...  
45217  United-States        0         <=50K  
45218  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[45222 rows x 12 columns]

# 2.3.3

In [27]:
file.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K

In [28]:
file.tail(3)

age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
45220    Own-child  Other   Male              40  United-States     5455   
45221      Husband  White   Male              60  United-States        0   

      income_status  
45219         <=50K  
45220         <=50K  
45221          >50K

In [29]:
file.shape

(45222, 12)

In [30]:
file.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [31]:
file.iloc[43000:43003]

age         workclass  education_num marital_status       occupation  \
43000   23           Private              9  Never-married            Sales   
43001   54  Self-emp-not-inc             13  Never-married  Exec-managerial   
43002   21           Private             10  Never-married     Adm-clerical   

        relationship   race  gender  hours_per_week native_country  capital  \
43000      Own-child  White  Female              15  United-States     8614   
43001  Not-in-family  White    Male              25  United-States        0   
43002      Own-child  White    Male              40  United-States     2597   

      income_status  
43000          >50K  
43001         <=50K  
43002         <=50K

In [32]:
file.loc[file['gender'] == 'Male']

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
7       52  Self-emp-not-inc              9  Married-civ-spouse   
...    ...               ...            ...                 ...   
45216   48         Local-gov             14            Divorced   
45217   33           Private             13       Never-married   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White   Male              40   
1        Exec-managerial        Husband  White   Male              13   
2      Handlers-cleaners  Not-in-family  White   Male              40   
3      Handlers-cleaners        Husband  Other   Male              40   
7        Exec-managerial        Husband  White   Male              45   
...                  ...            ...    ...    ...             ...   
45216      Other-service  Not-in-family  White   Male              40   
45217     Prof-specialty      Own-child  White   Male              40   
45219     Prof-specialty        Husband  White   Male              50   
45220       Adm-clerical      Own-child  Other   Male              40   
45221    Exec-managerial        Husband  White   Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
7      United-States        0          >50K  
...              ...      ...           ...  
45216  United-States        0         <=50K  
45217  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[30527 rows x 12 columns]

# 3.3.2

In [19]:
import pandas as pd
import numpy as np
from math import sqrt

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"

tab = pd.read_csv(url)

xmin = tab['sepal_length_cm'].min()
xmax = tab['sepal_length_cm'].max()

std = np.std(tab['sepal_width_cm'])
mean = np.mean(tab['sepal_width_cm'])

def norm_minmax(x):
    return (x-xmin)/(xmax-xmin)

def z_scaling(x):
    return (x - mean)/std

tab['sepal_length_cm'] = tab['sepal_length_cm'].apply(norm_minmax)
tab['sepal_width_cm'] = tab['sepal_width_cm'].apply(z_scaling)

tab

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]